// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fjumbncguszvqufuvyar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqdW1ibmNndXN6dnF1ZnV2eWFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNDQyNzMsImV4cCI6MjA2MzkyMDI3M30.DJyuq3LCLz53a7SBHngc3r3YKGU_jaR4Qj2DCK1RSeQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);